<div class="container ecpGlobal-margin">
<div class="row">
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
	<div class="panel-heading">
        <h5><i class="glyphicon glyphicon-user"></i> Registro de Usuario</h5>
	</div>
    <div class="panel-body">
	  <span class="help-block">
	    <h4>Enhorabuena!</h4>
        <p>Ya eres parte del El Club del Programador, s&oacute;lo una cosa m&aacute;s, te hemos enviado un correo electr&oacute;nico para que nos confirmes tu registro</p>
	  </span>
	</div>
    <div class="panel-footer clearfix">
      <div class="pull-right">
        <a href="home" class="btn btn-primary">Regresar</a>
      </div>
    </div>
  </div>
</div>
</div>
</div>