<div class="container ecpGlobal-margin">
<div class="row">
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
	<div class="panel-heading">
        <h5><i class="glyphicon glyphicon-user"></i> Registro de Usuario</h5>
	</div>
    <div class="panel-body">
	  <span class="help-block">
	    <h4>Gracias por confirmar tu registro</h4>
        <p> Inicia sesi&oacute;n para disfrutar de todo lo que te ofrecemos.</p>
	  </span>
	</div>
    <div class="panel-footer clearfix">
      <div class="pull-right">
        <a href="home" class="btn btn-primary">Regresar</a>
      </div>
    </div>
  </div>
</div>
</div>
</div>