<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Terms and Conditions</h4>
</div>
<div class="modal-body">
  <h4>1.1. Purpose</h4>
<p>The mission of LinkedIn is to connect the world’s professionals to enable them to be more productive and successful. 
To achieve our mission, we make services available through our websites, mobile applications, and developer platforms, 
to help you, your connections, and millions of other professionals meet, exchange ideas, learn, make deals, find 
opportunities or employees, work, and make decisions in a network of trusted relationships and groups.</p>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary" id="iAgree" data-dismiss="modal">He Le&iacute;do y acepto.</button>
</div>



