</div> <!-- Wrap Div -->
<div id="footer">
    <div class="container">
        <div class="row creditos">
              <div class="col-sm-3">
               <div class="text-center footertext">
                  <a href="#" class="footer-link">Sobre nosotros</a>
               </div>
              </div>
              <div class="col-sm-3">
                <div class="text-center footertext">
                  <a href="#" class="footer-link"> Blog</a>
                </div>
              </div>
              <div class="col-sm-3">
                <div class="text-center footertext">
                  <a href="#" class="footer-link"> Contacto</a>
                </div>
              </div>
			  <div class="col-sm-3">
                <div class="text-center">
                  <a href="http://www.facebook.com/pages/El-Club-del-Programador/247878995262739" target="_blank"> <img src="views/default/images/site/facebook.png" alt="Facebook"/></a>
                  <a href="http://twitter.com/c_programador" target="_blank"><img src="views/default/images/site/twitter.png" alt="Twitter" /></a>
                  <a href="http://feeds.feedburner.com/elclubdelprogramador" target="_blank"><img src="views/default/images/site/rss.png" alt="RSS" /></a>
                </div>
              </div>
            </div>
</div>	
<script type="text/javascript" src="views/default/js/bootstrap.min.js"></script>
</body> 
</html>