<!-- Main content of the splash screen -->
<div class="section ecpsplash-bg">
  <div class="container white" >
   <div class="row">
      <div class="col-xs-12">
        <h3 class="text-center">Aprende, programa, comparte</h3>
      </div>
    </div>
    <div class="row">
        <form class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-lg-6 " role="search" action="">
          <div class="input-group">
            <input class="form-control" placeholder="Quiero aprender..." name="search" id="search" type="text">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
            </div>
          </div>
        </form>
    </div>
  </div>
</div> 

<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
      <h4 class="text-center">Tutoriales, tips, herramientas y recursos para el desarrollador</h4>
      <h5 class="text-center">Lenguajes de programaci&oacute;n disponibles</h5>
      </div>
      </div>
      <div class="row">
      <!-- START langs -->
      <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 ">
        <div class="panel panel-default grey">
          <div class="panel-body">
            <div class="text-center">
              <a class="blackLink" href="snippets/category/{categoryName}">
              {categoryName}
              </a>
            </div>
          </div>
        </div>  
      </div>
    <!-- END langs -->
    </div>
  </div>
</div>