<!-- Main content of the splash screen -->
<div class="section ecpsplash-bg">
  
  <div class="container white" >
    <h3 class="text-center">Aprende, programa, comparte</h3>
    <form class="navbar-form text-center" role="search">
      <div class="input-group">
        <input class="form-control ecpmainsearchlength" placeholder="Quiero aprender..." name="search" id="search" type="text">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </form>
  </div>
</div> 

<div class="section">
  <div class="container">
    <div class="row">
      <h4 class="text-center">Tutoriales, tips, herramientas y recursos para el desarrollador</h4>
      <h5 class="text-center">Lenguajes de programaci&oacute;n disponibles</h5>
      <!-- START langs -->
      <div class="col-md-2">
        <div class="panel panel-default grey">
          <div class="panel-body">
            <div class="text-center">
              <a class="blackLink" href="snippets/category/{categoryName}">
              {categoryName}
              </a>
            </div>
          </div>
        </div>  
      </div>
    <!-- END langs -->
    </div>
  </div>
</div>