<div class="container">
  <div class="row ecpGlobal-margin">
    <div class="col-md-6 col-md-offset-3">  
      <div class="panel panel-default">
        <div class="panel-heading">
          <h5><i class="glyphicon glyphicon-user"></i> {heading}</h5>
	    </div>
        <div class="panel-body"><span class="help-block">{content}</span></div>
        <div class="panel-footer clearfix">
          <div class="pull-right">
            <a href="home" class="btn btn-primary">Regresar</a>
          </div>
        </div>
      </div>
	</div>
  </div>
</div>