<div class="container ecpGlobal-margin">
<div class="row">
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
	<div class="panel-heading">
        <h5><i class="glyphicon glyphicon-user"></i> Recuperar Password</h5>
	</div>
    <div class="panel-body">
	  <span class="help-block">Se ha enviado un mail a tu cuenta con las instrucciones para recuperar tu password.</span>
	</div>
    <div class="panel-footer clearfix">
      <div class="pull-right">
        <a href="home" class="btn btn-primary">Regresar</a>
      </div>
    </div>
  </div>
</div>
</div>
</div>