<div id="wrap" class="ecpGlobal-bg">
  <div role="navigation" class="navbar navbar-inverse navbar-fixed-top ecpnavbar-bg">
    <div class="container-fluid">
      <!-- Toggle for mobile -->
      <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button> 
        <a href="home" class="navbar-brand"><img src="views/default/images/site/titulo.png"></a>
      </div>
	  <!-- Nav Links-->
	  <div id="navbarCollapse" class="collapse navbar-collapse">
	    <div class="col-sm-3 col-md-3">
         <form class="navbar-form" role="search">
           <div class="input-group">
             <input type="text" class="form-control" placeholder="Busca en todo el site" name="search" id="search">
             <div class="input-group-btn">
               <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
             </div>
           </div>
         </form>
       </div>
        <ul class="nav navbar-nav navbar-right">
		  <li class="dropdown dropdown-large">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle"><span class="fa fa-globe"></span></a>
			<ul class="dropdown-menu dropdown-menu-large row">
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header"><span class="fa fa-code pull-right"></span> Snippets</li>
							<li><a href="snippets">Repositorio</a></li>
							<li><a href="snippets/add">Agrega tu Snippet</a></li>
							<li class="divider"></li>
							<li class="dropdown-header"><span class="fa fa-bookmark pull-right"></span> Bookmarks</li>
							<li><a href="links">Explora</a></li>
							<li><a href="links/add">Agrega tu Enlace</a></li>
							<li class="divider"></li>
							<li class="dropdown-header"><span class="fa fa-rss pull-right"></span> Feeds RSS</li>
							<li><a href="#">Mis RSS</a></li>
							<li><a href="#">Buscar Canales</a></li>
						</ul>
					</li>
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header"><span class="fa fa-book pull-right"></span> Tutoriales </li>
							<li><a href="tuts">Aprende un lenguaje</a></li>
							<li><a href="http://www.roesler-ac.de/wolfram/hello.htm">How-to</a></li>
							<li><a href="resources">Recursos</a></li>
							<li><a href="apis">API's</a></li>
							<li class="divider"></li>
							<li class="dropdown-header"><span class="fa fa-graduation-cap pull-right"></span> Courses</li>
							<li><a href="#">Single button dropdowns</a></li>
						</ul>
					</li>
					<li class="col-sm-3">
						<ul>
						<li class="dropdown-header">Jobs</li>
							<li><a href="#">Basic example</a></li>
							<li><a href="#">Button toolbar</a></li>
							<li class="divider"></li>
							<li class="dropdown-header"><span class="fa fa-cubes pull-right"></span> Projects</li>
							<li><a href="#">Nesting</a></li>
							<li><a href="#">Vertical variation</a></li>
							<li class="divider"></li>
							<li class="dropdown-header"><span class="fa fa-users pull-right"></span> Groups</li>
							<li><a href="#">Single button dropdowns</a></li>	
						</ul>
					</li>
				<li class="col-sm-3">
						<ul>
							<li class="dropdown-header"><span class="fa fa-shopping-cart pull-right"></span> Market</li>
							<li><a href="#">Basic example</a></li>
							<li><a href="#">Button toolbar</a></li>
							<li class="divider"></li>
							<li class="dropdown-header"><span class="fa fa-question-circle pull-right"></span> Q&A</li>
							<li><a href="#">Vertical variation</a></li>
							<li class="divider"></li>
							<li class="dropdown-header"><span class="fa fa-shopping-cart pull-right"></span> Store</li>
							<li><a href="#">Single button dropdowns</a></li>
						</ul>
					</li>
				</ul>
	      </li>
	       <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle"><span class="fa fa-bullhorn"> <span class="label label-danger">!</span></span></a>
			  <ul class="dropdown-menu dropdownmenu-custom">
			    <li><a href="#"><span class="fa fa-inbox pull-right"></span> Inbox</a></li>
				<li class="divider"></li>
				<li><a href="#"><span class="fa fa-calendar pull-right"></span> Eventos</a></li>
				<li><a href="#"> Notificaciones <span class="badge pull-right">6</span> </a></li>
				<li><a href="#"><span class="fa fa-flag pull-right"></span>Alertas</a></li>
				<li><a href="#"><span class="fa fa-list pull-right"></span> To Do</a></li>
			   </ul>
	       </li>
		    <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle"><span class="fa fa-comment"></span></a>
			  <ul class="dropdown-menu dropdownmenu-custom">
			    <li><a href="#"><span class="fa fa-inbox pull-right"></span> Inbox</a></li>
				<li class="divider"></li>
				<li><a href="#"><span class="fa fa-calendar pull-right"></span> Eventos</a></li>
				<li><a href="#"><span class="fa fa-bullhorn pull-right"></span> Notificaciones</a></li>
				<li><a href="#"><span class="fa fa-flag pull-right"></span>Alertas</a></li>
				<li><a href="#"><span class="fa fa-list pull-right"></span> To Do</a></li>
			   </ul>
	       </li>
		    <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle"> <i>{username}</i><b class="caret"></b></a>
			   <ul class="dropdown-menu dropdownmenu-custom">
			    <li><a href="#"><span class="fa fa-dashboard pull-right"></span> Dashboard</a></li>
				<li><a href="#"><span class="fa fa-cogs pull-right"></span> Mi Perfil</a></li>
				<li class="divider"></li>
				<li><a href="authenticate/logout"><span class="fa fa-sign-out pull-right" ></span> Cerrar Sesion</a></li>
			   </ul>
	       </li>
	     </ul>
	   </div>
	 </div> 
  </div>
  <script type="text/javascript" src="lib/search/search_animation.js"></script>