<link rel="stylesheet" href="lib/tutorials/list.css"></link>
<div class="container-fluid ecpGlobal-margin">
  <ul class="breadcrumb">
        <li><a href="home">Home</a></li>
        <li class="active">Tutoriales</li>
  </ul>
  <div class="row">
    <div class="col-md-12">
      <h4>Tutoriales Disponibles</h4>
    </div>
  </div>
  <div class="row">
    <!-- START langs -->
    <div class="col-md-2">
      <div class="pin">
        <img src="views/default/images/lang/{category_image}" />
        <h4><a href="tuts/{category_name}">{category_name}</a></a></h4>
        <p>
        <br>Total Tutoriales: {total_tuts}
        <br>Usuarios activos: 256

        </p>
	    </div>  
	  </div>
	<!-- END langs -->
  </div>
</div>