<div class="container-fluid ecpGlobal-margin">
<div class="row">
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-primary">
	<div class="panel-heading">
        <h5><span class="fa fa-eye-slash"></span> No encontramos lo que buscas</h5>
	</div>
    <div class="panel-body">
	  <span class="help-block">
	    <h4>Has solicitado un recurso que no existe actualmente</h4>
        <p> Intenta buscar otro contenido.</p>
	  </span>
	</div>
    <div class="panel-footer clearfix">
      <div class="pull-right">
        <a href="home" class="btn btn-primary">Llevame al Dashboard</a>
      </div>
    </div>
  </div>
</div>
</div>
    <!-- START langs -->
	<!-- END langs -->
</div>