<!-- Main content of the splash screen -->
<div class="section ecpsplash-bg">
  <div class="container white" >
   <div class="row">
      <div class="col-xs-12">
        <h1 >{cat}</h1>
        </div>
        <div class="col-xs-9">
        <h5>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h5>
      </div>
    </div>
  </div>
</div> 