<!-- Main content of the splash screen -->
<div class="category-section category-bg">
  <div class="container white" >
   <div class="row snippet-content">
     <div class="col-xs-2">
       <a href="#"><img src="{category_image}" class="img-thumbnail" id="img-snippet" alt="{category_name}">
       </a>
     </div>       
     <div class="col-xs-10">
        <h1 >{category_name}</h1>
        <p>
          {category_description}
        </p>
    </div>
    </div>
  </div>
</div> 