<!-- Main content of the splash screen -->
<div class="category-section" style="background-image: url({category_image_front});">
  <div class="container white" >
   <div class="row snippet-content">
     <div class="col-xs-2">
       <a href="#"><img src="{category_image}" class="img-thumbnail" id="img-category" alt="{category_name}">
       </a>
     </div>       
     <div class="col-xs-10">
        <h2>{category_name}</h2>
        <p>
          {category_description}
        </p>
    </div>
    </div>
  </div>
</div> 
<div>
   <p>seccion tutoriales</p>
   <!-- START category_tuts -->
   {id}-{title}
   <!-- END category_tuts -->
<p>seccion API</p>
<p>seccion mashups</p>
<p>seccion articulos</p>
<p>seccion snippets</p>
<p>seccion Links</p>
</div>